### ISSUE TITLE
When "forwarding" a stream directly to MediaMTX, MediaMTX does not see the video track

### ISSUE THREAD

**Issue by xaionaro** [xaionaro-go/avd#1]
This is just a reminder for myself about the bug mentioned in the title.

The config:
```yaml
ports:
- address: tcp:0.0.0.0:1946
  mode: "publishers"
  protocol_handler:
    rtmp: {}
- address: tcp:0.0.0.0:1945
  mode: "consumers"
  protocol_handler:
    rtmp: {}
- address: tcp:127.0.0.1:8565
  mode: "publishers"
  protocol_handler:
    rtsp:
      transport_protocol: ""
- address: tcp:0.0.0.0:8564
  mode: "consumers"
  protocol_handler:
    rtsp:
      transport_protocol: ""
endpoints:
  pixel/dji-osmo-pocket-3-0:
    forwardings:
    - destination:
        local:
          route: pixel/dji-osmo-pocket-3-merged
          publish_mode: shared-takeover
      recoding:
        video_track_configs:
        - input_track_ids:
          - 0
          output_track_ids:
          - 0
          codec_name: copy
        audio_track_configs:
        - input_track_ids:
          - 1
          output_track_ids:
          - 1
          codec_name: copy
  pixel/dji-osmo-pocket-3-1:
    forwardings:
    - destination:
        local:
          route: pixel/dji-osmo-pocket-3-merged
          publish_mode: shared-takeover
      recoding:
        video_track_configs:
        - input_track_ids:
          - 0
          output_track_ids:
          - 2
          codec_name: copy
        audio_track_configs:
        - input_track_ids:
          - 1
          output_track_ids:
          - 3
          codec_name: copy
  pixel/dji-osmo-pocket-3-merged:
    forwardings:
    - destination:
        url: rtmp://127.0.0.1:1935/pixel/dji-osmo-pocket-3?user=********&pass=********
```

The `127.0.0.1:1935` is listened by MediaMTX. For some reason it does not see the video track, while both ffmpeg and mpv do see it (if I stream it to them).
